CREATE TABLE omg_import(
	ID int(11) NOT NULL AUTO_INCREMENT,
	ACTIVE char(1) NOT NULL DEFAULT 'Y',
	XML_ID varchar(255) NOT NULL,
	NAME varchar(255) NOT NULL,
	FILE varchar(255) NOT NULL,
	FILE_TYPE varchar(10) NOT NULL,
	TYPE varchar(10) NOT NULL,
	STEP int(11) NOT NULL DEFAULT '30',
	MISSING_ITEMS char(1) NOT NULL DEFAULT '0',
	MISSING_SECTIONS char(1) NOT NULL DEFAULT '0',
	MISSING_OFFERS char(1) NOT NULL DEFAULT '0',
	IMAGES_DIR varchar(255) NOT NULL,
	
	IBLOCK_ID int(11) NOT NULL,
	SECTION_ID int(11) NOT NULL,
	
	FORM_ID int(11) NOT NULL,
	
	FIRST_NAMES char(1) NOT NULL DEFAULT 'Y',
	DELIMETER varchar(10) NOT NULL,
	
	ELEMENTS_CHUNK varchar(255) NOT NULL,
	ELEMENT_CHUNK varchar(255) NOT NULL,
	SECTIONS_CHUNK varchar(255) NOT NULL,
	SECTION_CHUNK varchar(255) NOT NULL,
	OFFERS_CHUNK varchar(255) NOT NULL,
	OFFER_CHUNK varchar(255) NOT NULL,
	
	FIELDS text NOT NULL,
	PRIMARY KEY (ID)
);